### ISSUE TITLE
Add support for Jack Audio

### ISSUE THREAD

**Issue by ycollet** [kometbomb/klystron#14]
Hello,

Currently, klystrack work on Alsa.
It should be nice to be able to have a version of klystrack which works with Jack.

Best regards,

YC

**Comment by kometbomb** [comment]
Could you check if this works?

`export SDL_AUDIODRIVER=jack`

https://discourse.libsdl.org/t/sdl-now-with-jack-support/22607

ma 24. syysk. 2018 klo 12.08 ycollet (notifications@github.com) kirjoitti:

**Comment by ycollet** [comment]
Thanks, I will try this ASAP.

----- Mail original -----
De: "Tero Lindeman" <notifications@github.com>
À: "kometbomb/klystron" <klystron@noreply.github.com>
Cc: "ycollet" <ycollette.nospam@free.fr>, "Author" <author@noreply.github.com>
Envoyé: Lundi 24 Septembre 2018 12:02:39
Objet: Re: [kometbomb/klystron] Add support for Jack Audio (#14)

Could you check if this works? 

`export SDL_AUDIODRIVER=jack` 

https://discourse.libsdl.org/t/sdl-now-with-jack-support/22607 

ma 24. syysk. 2018 klo 12.08 ycollet (notifications@github.com) kirjoitti:

**Comment by ycollet** [comment]
It works.

I will try to find if it's possible to build a klystrack executable with jack set by default now.

----- Mail original -----
De: "Tero Lindeman" <notifications@github.com>
À: "kometbomb/klystron" <klystron@noreply.github.com>
Cc: "ycollet" <ycollette.nospam@free.fr>, "Author" <author@noreply.github.com>
Envoyé: Lundi 24 Septembre 2018 12:02:39
Objet: Re: [kometbomb/klystron] Add support for Jack Audio (#14)

Could you check if this works? 

`export SDL_AUDIODRIVER=jack` 

https://discourse.libsdl.org/t/sdl-now-with-jack-support/22607 

ma 24. syysk. 2018 klo 12.08 ycollet (notifications@github.com) kirjoitti:

**Comment by kometbomb** [comment]
You could simply start it with a script that sets the environment variable:

Contents of klystrack-jack.sh:

SDL_AUDIODRIVER=jack klystrack

ma 24. syysk. 2018 klo 13.57 ycollet (notifications@github.com) kirjoitti:

**Comment by ycollet** [comment]
Yes, yes, this is a solution.
I have made a rpm package of klystrack for Fedora. Have a look here:
https://copr.fedorainfracloud.org/coprs/ycollet/linuxmao/

I will install an executable script: klystrack-jack which is a bash script with this variable set.
This is a very simple solution ...

----- Mail original -----
De: "Tero Lindeman" <notifications@github.com>
À: "kometbomb/klystron" <klystron@noreply.github.com>
Cc: "ycollet" <ycollette.nospam@free.fr>, "Author" <author@noreply.github.com>
Envoyé: Lundi 24 Septembre 2018 13:09:26
Objet: Re: [kometbomb/klystron] Add support for Jack Audio (#14)

You could simply start it with a script that sets the environment variable: 

Contents of klystrack-jack.sh: 

SDL_AUDIODRIVER=jack klystrack 

ma 24. syysk. 2018 klo 13.57 ycollet (notifications@github.com) kirjoitti:

**Comment by kometbomb** [comment]
Yeah, definitely should. I guess it should also come with a script that
does just that.

ma 24. syysk. 2018 klo 14.25 ycollet (notifications@github.com) kirjoitti:

**Comment by ycollet** [comment]
OK, fine. Maybe it's time now to ... close the bug report ... Sniff ... :)

----- Mail original -----
De: "Tero Lindeman" <notifications@github.com>
À: "kometbomb/klystron" <klystron@noreply.github.com>
Cc: "ycollet" <ycollette.nospam@free.fr>, "Author" <author@noreply.github.com>
Envoyé: Lundi 24 Septembre 2018 15:52:25
Objet: Re: [kometbomb/klystron] Add support for Jack Audio (#14)

Yeah, definitely should. I guess it should also come with a script that 
does just that. 

ma 24. syysk. 2018 klo 14.25 ycollet (notifications@github.com) kirjoitti:
